
name: Docker Build and Push to ECR Repository

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Display Environment Variables
        run: |
          echo "GITHUB_HEAD_REF : $GITHUB_HEAD_REF"
          echo "GITHUB_EVENT_NAME : $GITHUB_EVENT_NAME"
          echo "GITHUB_WORKSPACE : $GITHUB_WORKSPACE"
          echo "GITHUB_SHA : $GITHUB_SHA"
          echo "GITHUB_REF_TYPE : $GITHUB_REF_TYPE"
          echo "GITHUB_REF_NAME : $GITHUB_REF_NAME"
          echo "GITHUB_ACTION : $GITHUB_ACTION"